title: Piyush Patil
logo: /docs/_img/Passport_Piyush_patil.jpg
show download: False
theme: jekyll-theme-minimal
url: https://patilpiyush.github.io
baseurl: /profile/docs/DE/                      # place folder name if the site is served in a subfolder

