title: Piyush Patil
logo: /docs/_img/Passport_Piyush_patil.jpg
show download: False
theme: jekyll-theme-minimal
url: https://patilpiyush.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /profile/docs/EN/      # place folder name if the site is served in a subfolder

